### ISSUE TITLE
Still an occasional error when setting up map

### ISSUE THREAD

**Issue by ledpup** [ledpup/ClimateExplorer#121]
Unhandled exception rendering component: Cannot read properties of null (reading 'addLayer')
      TypeError: Cannot read properties of null (reading 'addLayer')
          at i.addTo (https://unpkg.com/leaflet@1.7.1/dist/leaflet.js:5:63275)
          at https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:3332
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:3306)
          at Object.St [as invokeJSFromDotNet] (https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:59938)
          at _mono_wasm_invoke_js_blazor (https://www.climateexplorer.net/_framework/dotnet.6.0.9.o04gyxc4n3.js:1:173403)
          at wasm://wasm/008e5b7a:wasm-function[158]:0x163db
          at wasm://wasm/008e5b7a:wasm-function[106]:0x70e3
          at wasm://wasm/008e5b7a:wasm-function[105]:0x5ffc
          at wasm://wasm/008e5b7a:wasm-function[7273]:0x18069d

Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'addLayer')
TypeError: Cannot read properties of null (reading 'addLayer')
    at i.addTo (https://unpkg.com/leaflet@1.7.1/dist/leaflet.js:5:63275)
    at https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:3332
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://www.climateexplorer.net/_framework/blazor.webassembly.js:1:59938)
    at _mono_wasm_invoke_js_blazor (https://www.climateexplorer.net/_framework/dotnet.6.0.9.o04gyxc4n3.js:1:173403)
    at wasm://wasm/008e5b7a:wasm-function[158]:0x163db
    at wasm://wasm/008e5b7a:wasm-function[106]:0x70e3
    at wasm://wasm/008e5b7a:wasm-function[105]:0x5ffc
    at wasm://wasm/008e5b7a:wasm-function[7273]:0x18069d
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at DPBlazorMapLibrary.Layer.AddTo(Map map)
   at DPBlazorMapLibrary.LayerFactory.CreateMarkerAndAddToMap(LatLng latLng, Map map, MarkerOptions options)
   at ClimateExplorer.Visualiser.Shared.MapContainer.EnsureMapMarkers()
   at ClimateExplorer.Visualiser.Shared.MapContainer.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by ledpup** [comment]
I made a couple more changes (for instance checking that JsRuntime was not null) and have not seen this issue for some time, on multiple devices.
