### ISSUE TITLE
Trendline has stopped working (javascript issue)

### ISSUE THREAD

**Issue by ledpup** [ledpup/ClimateExplorer#98]

**Comment by ledpup** [comment]
This is caused by the refactor of the scales on the chart, from using an anonymous type to an expandoobject. Somehow the options are been seen as undefined by the time that the trendline component comes to use it. It doesn't affect chart otherwise, hoeever.


ClimateExplorer.Visualiser.Pages.Index[0]
      Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'options')
      TypeError: Cannot read properties of undefined (reading 'options')
          at https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline:17:823
          at Array.forEach (<anonymous>)
          at addFitter (https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline:17:775)
          at https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline:17:310
          at Array.forEach (<anonymous>)
          at Object.afterDatasetsDraw (https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline:17:198)
          at J (https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js:13:7902)
          at Ns._notify (https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js:13:85041)
          at Ns.notify (https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js:13:84862)
          at dn.notifyPlugins (https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js:13:102859)
         at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Blazorise.Charts.JSChartModule.Update(String canvasId)
         at Blazorise.Charts.BaseChart`4.<Update>d__21[[Blazorise.Charts.ChartDataset`1[[System.Nullable`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Blazorise.Charts, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null],[System.Nullable`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Blazorise.Charts.ChartOptions, Blazorise.Charts, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null],[Blazorise.Charts.ChartModel, Blazorise.Charts, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
